In [3]:
import pandas as pd 
import numpy as np 
import scipy.optimize as opt 
from sklearn import preprocessing 
from sklearn.preprocessing import LabelEncoder

In [4]:
data=pd.read_csv(r'C:\Users\kowsar\PycharmProjects\PycharmProjects\pythonProject\venv\Scripts\lung.csv')

In [7]:
h=data.head() 
h

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0

DATA CLEANING

In [8]:
g=data['LUNG_CANCER']
l=LabelEncoder()
encoded_data=l.fit_transform(g)
data['LUNG_CANCER']=encoded_data

In [9]:
g1=data['GENDER']
l1=LabelEncoder()
encoded_data1=l1.fit_transform(g)
data['GENDER']=encoded_data1

In [10]:
h1=data.head()
h1

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        1               2        2              1   
1       1   74        2               1        1              1   
2       0   59        1               1        1              2   
3       0   63        2               2        2              1   
4       0   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0

In [11]:
m_d=data.isnull().sum()
m_d

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [12]:
data.dtypes

GENDER                   int64
AGE                      int64
SMOKING                  int64
YELLOW_FINGERS           int64
ANXIETY                  int64
PEER_PRESSURE            int64
CHRONIC DISEASE          int64
FATIGUE                  int64
ALLERGY                  int64
WHEEZING                 int64
ALCOHOL CONSUMING        int64
COUGHING                 int64
SHORTNESS OF BREATH      int64
SWALLOWING DIFFICULTY    int64
CHEST PAIN               int64
LUNG_CANCER              int64
dtype: object

In [13]:
x=np.asarray(data[['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS','ANXIETY', 'PEER_PRESSURE', 'CHRONIC DISEASE', 'WHEEZING', 'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH', 'SWALLOWING DIFFICULTY', 'CHEST PAIN']])
x[0:5]

array([[ 1, 69,  1,  2,  2,  1,  1,  2,  2,  2,  2,  2,  2],
       [ 1, 74,  2,  1,  1,  1,  2,  1,  1,  1,  2,  2,  2],
       [ 0, 59,  1,  1,  1,  2,  1,  2,  1,  2,  2,  1,  2],
       [ 0, 63,  2,  2,  2,  1,  1,  1,  2,  1,  1,  2,  2],
       [ 0, 63,  1,  2,  1,  1,  1,  2,  1,  2,  2,  1,  1]], dtype=int64)

In [52]:
y=np.asarray(data['LUNG_CANCER'])
y[0:5]
f=data['LUNG_CANCER']
f.value_counts()

LUNG_CANCER
1    270
0     39
Name: count, dtype: int64

In [55]:
x

array([[ 1, 69,  1, ...,  2,  2,  2],
       [ 1, 74,  2, ...,  2,  2,  2],
       [ 0, 59,  1, ...,  2,  1,  2],
       ...,
       [ 1, 58,  2, ...,  1,  1,  2],
       [ 1, 67,  2, ...,  2,  1,  2],
       [ 1, 62,  1, ...,  1,  2,  1]], dtype=int64)

In [56]:
#Normalizing 
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
x=scaler.fit(x).transform(x)


In [57]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=4)

print(x_train.shape, y_train.shape)
print(x_train)
print(x_test.shape, y_test.shape)

(247, 13) (247,)
[[-2.63117406 -0.32611168  0.88083033 ...  0.74873631 -0.94029056
  -1.12047956]
 [ 0.38005848  1.62582068  0.88083033 ...  0.74873631 -0.94029056
   0.892475  ]
 [ 0.38005848  1.62582068  0.88083033 ...  0.74873631  1.06350105
   0.892475  ]
 ...
 [ 0.38005848 -0.44810745 -1.13529242 ... -1.33558369  1.06350105
   0.892475  ]
 [ 0.38005848  1.13783759 -1.13529242 ...  0.74873631 -0.94029056
   0.892475  ]
 [ 0.38005848 -0.69209899  0.88083033 ...  0.74873631 -0.94029056
  -1.12047956]]
(62, 13) (62,)


In [58]:
#increasing my dimention by the use of different Kernel function
from sklearn import svm
clf=svm.SVC(kernel='rbf')
clf.fit(x_train, y_train)

SVC()

In [59]:
yhat=clf.predict(x_test)
print(yhat[0:10])
print(y_test[0:10])
np.sum(yhat==1),yhat.shape

[0 1 1 1 1 1 1 1 0 1]
[0 1 1 1 1 1 1 1 0 1]


(56, (62,))

In [61]:
#Evaluation
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat, pos_label=1)

1.0

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        56

    accuracy                           1.00        62
   macro avg       1.00      1.00      1.00        62
weighted avg       1.00      1.00      1.00        62

